services:
  webserver:
    image: tugboatqa/php:8.3-apache
    default: true
    depends: database
    commands:
      init:
        # Install opcache and mod-rewrite
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        # Link the document root to the expected path.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        # Link the config directory.
        - ln -snf "${TUGBOAT_ROOT}/config" "${DOCROOT}/../config"

        # - echo "if (file_exists(\$app_root . '/' . \$site_path . '/settings.tugboat.php')) { include \$app_root . '/' . \$site_path . '/settings.tugboat.php';}" >> ${DOCROOT}/web/sites/default/settings.php
      update:
        - composer self-update
        - composer install --optimize-autoloader
        - cp .tugboat/tugboat.settings.php $TUGBOAT_ROOT/web/sites/default/settings/local.php

        - |
          if [ -f "${TUGBOAT_ROOT}/files.tgz" ]; then \
            rm -rf "${DOCROOT}/sites/default/files" \
            tar -xvzf files.tgz \
            mv files "${DOCROOT}/sites/default" \
          fi
      build:
        

  database:
    image: tugboatqa/mariadb:10.11
    commands:
      init:
        - mysql -e "SET GLOBAL max_allowed_packet=536870912;"
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf

